version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - .:/usr/app
    links:
      - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"